#include <GL/glut.h>
#include <GL/gl.h>
#include <iostream>
#include <string>
#include <fstream>
#include <vector>
#include <sstream>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include <algorithm>
#include <limits>
#include <numeric>
#include <dirent.h>

#include <QColor>
#include <QDebug>
#include <QtMath>
#include <QWidget>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QDir>
#include <QGraphicsPixmapItem>
#include <QStringList>
#include <QMessageBox>
#include <QToolTip>
#include <QWidget>
#include <QOpenGLWidget>
#include <QOpenGLFunctions>
#include <QOpenGLVertexArrayObject>
#include <QOpenGLBuffer>
#include <QOpenGLFramebufferObject>
#include <QOpenGLTexture>
#include <QOpenGLShaderProgram>
#include <QOpenGLDebugLogger>
#include <QImage>
#include <QVector>
#include <QMatrix>
#include <QTime>
#include <QTimer>
#include <QKeyEvent>
#include <QtGlobal>
#include <QtCore/qmath.h>

#include "modelloader.h"
#include "branch.h"
#include "init.h"
#include "readinput.h"
#include "functions.h"
#include "severity.h"
